import Head from 'next/head';
import Image from 'next/image';
import lofi from '../public/lofi.jpg';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 py-5'>
        <section className='min-h-screen'>
          <nav className='px-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-bold'>Ambition</h1>
            <ul className='flex items-center font-semibold space-x-6'>
              <li>Home</li>
              <li>Schedule</li>
              <li>About</li>
              <li>Contact</li>
            </ul>
          </nav>

          <div className='bg- text-center p-10'>
            <h2 className='text-5xl py-2 font-bold text-teal-600'>Ambition Library.</h2>
            <h3 className='text-2xl py-2 font-semibold'>Your own space to study.</h3>
            <p className='text-md py-5'>Can’t focus? Create your own study rooms that help you study and do deep work. All rooms are open 24/7.</p>
            <p><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white p-2 rounded-md' href="#"> Join Now </a></p>
          </div>
          <div className='relative mx-auto  rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image alt="" src={lofi} layout="fill" objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-lg font-semibold'>Services we offer.</h3>
          </div>
          <div className='lg:flex gap-10'>         
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2 '>Newspapers</h3>
              <p className='py-2'> We provide Free Newspapers to our students free of cost.</p>
              <h4 className='text-teal-600 py-4'>Newspapers:</h4>
              <p className='text-gray-800 py-1'>The Hindu</p>
              <p className='text-gray-800 py-1'>The Indian Express</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2'>Air-Conditioned rooms</h3>
              <p className='py-2'>We provide fully Air-conditioned Rooms to our students.</p>
              <h4 className='text-teal-600 py-4'>other facilities:</h4>
              <p className='text-gray-800 py-1'>Electrical outlets at ever desk</p>
              <p className='text-gray-800 py-1'>desk modified for privacy</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2 '>Unlimited wifi</h3>
              <p className='py-2'>We provide free 5g wifi with download speed upto 200 Mbps</p>
              <h4 className='text-teal-600 py-4'>List of Wifi</h4>
              <p className='text-gray-800 py-1'>Airtel 5g</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h2 className='text-lg font-semibold'>PLANS:</h2>
          </div>
          <div className='lg:flex justify-evenly gap-10'>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2'>8 Hours Plan</h3>
              <p className='py-2'>You can study/work for 8 hours per day.</p>
              <h4 className='text-teal-600 py-4'>Rate:</h4>
              <p className='text-gray-800 py-1'>Rs.600/month</p>
              <p className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white p-2 rounded-md'>Book now</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2'>8-12 Hours Plan</h3>
              <p className='py-2'>You can study/work for 8-12 hours per day.</p>
              <h4 className='text-teal-600 py-4'>Rate:</h4>
              <p className='text-gray-800 py-1'>Rs.700/month</p>
              <p className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white p-2 rounded-md'>Book now</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10'>
              <h3 className='text-lg font-medium pt-5 pb-2'>24 Hour plan</h3>
              <p className='py-2'>get a life or see a doctor every day.</p>
              <h4 className='text-teal-600 py-4'>Rate:</h4>
              <p className='text-gray-800 py-1'>Rs.1000/month</p>
              <p className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white p-2 rounded-md'>Book now</p>
            </div>
          </div>

        </section>

      </main>

    </div>
  )
}
